### ISSUE TITLE
Patch Status Report: Undefined Constant `FORMAT_JSON`

### ISSUE THREAD

**Issue by pykettk** [robaimes/module-quality-patches-ui#1]
# Description
Navigating to the patch status page in the admin shows the following error:
![quality-patches-error](https://user-images.githubusercontent.com/40261741/234580062-e1ba7d15-942c-4056-8cf4-7376d7b03ff0.png)

[The line in question can be found here](https://github.com/robaimes/module-quality-patches-ui/blob/main/Model/QualityPatches.php#L74). This constant belongs to the [`Magento\CloudPatches\Command\Process\ShowStatus`](https://github.com/magento/magento-cloud-patches/blob/develop/src/Command/Process/ShowStatus.php#L32) class.

I am able to run the quality patches tool successfully from the command line using `./vendor/bin/magento-patches status`:
![quality-patches-cli](https://user-images.githubusercontent.com/40261741/234580925-f6fd0f25-93a2-4e65-ba0e-2446f9fd2dbb.png)

# Steps to Replicate
- Log into the admin
- Navigate to `Reports -> Patch Status -> Quality Patches`
- Observe the aforementioned error

# Notes
- Local development environment
- Adobe Commerce Cloud 2.4.4 with B2B
- PHP 7.4.30
- Developer mode enabled

**Comment by robaimes** [comment]
This should be fixed in the latest version of the module @pykettk (as of `1.0.1`)

**Comment by pykettk** [comment]
I was using `1.0.0`. Updating to `1.1.1` resolved this issue. Thanks @robaimes 🙂
